CC = $(CROSS_COMPILE)gcc
AR = $(CROSS_COMPILE)ar
RM = rm

CFLAGS = -O0 -g -Wall -c -fPIC

OUTPUT_DIR = bin
OBJ_DIR = obj
PREFIX   ?= /usr/local/
API_DIR = ./VL53L0X_1.0.2


TARGET_LIB = $(OUTPUT_DIR)/libvl53l0x.a
TARGET_SO  = $(OUTPUT_DIR)/libvl53l0x.so

INCLUDES = \
	-I. \
	-I${API_DIR}/Api/core/inc \
	-I./platform/inc

VPATH = \
	${API_DIR}/Api/core/src \
	./platform/src/

LIB_SRCS = \
	vl53l0x_api_calibration.c \
	vl53l0x_api_core.c \
	vl53l0x_api_ranging.c \
	vl53l0x_api_strings.c \
	vl53l0x_api.c \
	vl53l0x_platform.c

LIB_OBJS  = $(LIB_SRCS:%.c=$(OBJ_DIR)/%.o)

EXAMPLES_SRC = $(wildcard examples/*)
EXAMPLES_BIN = $(EXAMPLES_SRC:examples/%.c=$(OUTPUT_DIR)/%)


.PHONY: all
all: ${TARGET_LIB}

shlib: ${TARGET_SO}

$(TARGET_LIB): $(LIB_OBJS)
	mkdir -p $(dir $@)
	$(AR) -rcs $@ $^

$(TARGET_SO): $(LIB_OBJS)
	$(CC) --shared -L$(OUTPUT_DIR) $^ -o $@

$(OBJ_DIR)/%.o:%.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

$(EXAMPLES_BIN): bin/%:examples/%.c
	mkdir -p $(dir $@)
	$(CC) -L$(OUTPUT_DIR) $^ -lvl53l0x  $(INCLUDES) -o $@

examples:${OUTPUT_DIR} ${TARGET_LIB} $(EXAMPLES_BIN)

.PHONY: clean
clean:
	-${RM} -rf ./$(OUTPUT_DIR)/*  ./$(OBJ_DIR)/*


install: $(TARGET_LIB)
	mkdir -p $(PREFIX)/include/VL53L0X_Rasp
	cp ./platform/inc/* $(PREFIX)/include/VL53L0X_Rasp
	cp ${API_DIR}/Api/core/inc/* $(PREFIX)/include/VL53L0X_Rasp
	mkdir -p $(PREFIX)/lib
	cp $(TARGET_LIB) $(PREFIX)/lib/libVL53L0X_Rasp.a


