odom_model_type: "diff-corrected"
odom_alpha5: 0.1
gui_publish_rate: 50.0
laser_max_beams: 30
min_particles: 500
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
odom_alpha1: 0.2
odom_alpha2: 0.2
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 2.0
update_min_d: 0.2
update_min_a: 0.5
odom_frame_id: "none"
base_frame_id: "base_link"
global_frame_id: "map"
use_map_topic: true
first_map_only: true
laser_max_range: 12.0
laser_min_range: 0.2
max_beams: 60
