obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.2
footprint: [[-0.165, -0.1], [-0.165, 0.1], [0.165, 0.1], [0.165, -0.1]]
inflation_radius: 0.5
transform_tolerance: 1.0
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
